### ISSUE TITLE
Disable logging in development mode?

### ISSUE THREAD

**Issue by nooblyf** [logtail/logtail-js#107]
Is there a way to just `console.log()` when in development mode? so i can see it in the terminal and not push the logs to the cloud

**Comment by nooblyf** [comment]
#22 works! but now i'm getting bunch of extra context, system details logged as well, is there a way to log the text only?

<img width="261" alt="Screenshot 2024-03-02 at 15 38 42" src="https://github.com/logtail/logtail-js/assets/54323745/f9a75e80-4bbd-417e-9a1e-480e58399f2f">

**Comment by curusarn** [comment]
Hi @nooblyf!

Thank you for reaching out!

Currently, there is no built-in option to customize the output as the output is intended to be consumed by Better Stack.

I can suggest two approaches here:

1) Make structured logs easier to read by getting rid of deeply nested fields: 
Set `contextObjectMaxDepth: 1` option when initializing Logtail logger.

2) Replace `logtail` functions in development with console.log
```
logtail = {};
logtail.fatal = console.log;
logtail.error = console.log;
logtail.warn = console.log;
logtail.info = console.log;
logtail.debug = console.log;
logtail.flush = function() {};
```

Let me know if either of those workarounds would work for you 🙏
 
Have a great weekend!

**Comment by nooblyf** [comment]
got it, thanks!
