### ISSUE TITLE
Unable to Determine Transport Target for @logtail/pino in the Vercel Environment

### ISSUE THREAD

**Issue by CHC383** [logtail/logtail-js#129]
Hi,

I am trying to use pino with @logtail/pino in my project. The project is deployed on Vercel with Node v22, and I was able to send logs in my local environment (both "next dev" and "next start”), but I am getting the error “unable to determine transport target for @logtail/pino” in the Vercel environment.

Error logs:
> {"level":50,"time":1733238342124,"pid":3,"hostname":"169.254.59.154","name":"console","err":{"type":"Error","message":"unable to determine transport target for \"@logtail/pino\"","stack":"Error: unable to determine transport target for \"@logtail/pino\"\n    at fixTarget (/var/task/node_modules/.pnpm/pino@9.5.0/node_modules/pino/lib/transport.js:160:13)\n    at /var/task/node_modules/.pnpm/pino@9.5.0/node_modules/pino/lib/transport.js:98:17\n    at Array.map (<anonymous>)\n    at transport (/var/task/node_modules/.pnpm/pino@9.5.0/node_modules/pino/lib/transport.js:95:59)\n    at normalizeArgs (/var/task/node_modules/.pnpm/pino@9.5.0/node_modules/pino/lib/tools.js:316:16)\n    at pino (/var/task/node_modules/.pnpm/pino@9.5.0/node_modules/pino/pino.js:90:28)\n    at /var/task/.next/server/chunks/7218.js:1:2395\n    at 51999 (/var/task/.next/server/chunks/7218.js:1:2399)\n    at t (/var/task/.next/server/webpack-runtime.js:1:143)\n    at 61917 (/var/task/.next/server/chunks/7218.js:1:190)","page":"/en/dashboard"},"msg":" ⨯”}

Logger creation:
``` typescript
import "server-only";
import "@logtail/pino";
import "pino-pretty";

import {
  Logger,
  LoggerOptions,
  pino,
  stdTimeFunctions,
  TransportTargetOptions,
} from "pino";

import { env } from "@/libs/env";

function getLoggerOption(): LoggerOptions<never, boolean> {
  const loggerOptions: LoggerOptions = {
    level: env.DEBUG_LOGGING ? "debug" : "info",
    timestamp: stdTimeFunctions.isoTime,
  };

  const targets: TransportTargetOptions[] = [];

  if (env.BETTERSTACK_LOG_TOKEN) {
    targets.push({
      target: "@logtail/pino",
      options: { sourceToken: env.BETTERSTACK_LOG_TOKEN },
    });
  }

  if (!env.PRODUCTION_ENV) {
    targets.push({
      target: "pino-pretty",
      options: {
        colorize: true,
      },
    });
  }

  if (targets.length > 0) {
    loggerOptions.transport = { targets: targets };
  }

  return loggerOptions;
}

function loggerSingleton(): Logger {
  const loggerOptions = getLoggerOption();
  const logger = pino(loggerOptions);

  return logger;
}
```

Any help would be appreciated, thanks!

**Comment by CHC383** [comment]
Thanks Petr for the quick response on this issue and the email. Inspired by https://github.com/pinojs/pino/issues/1964#issuecomment-2299477588, I finally got it work by adding `@logtail/pino` to `serverExternalPackages` in the Next JS config, looks like it is a webpack bundling issue. 

BTW, I also have `thread-stream` and `pino` in `serverExternalPackages` for resolving the worker bundling issue mentioned in [Bundling guide in Pino documentation](https://github.com/pinojs/pino/blob/main/docs/bundling.md)

**Comment by PetrHeinz** [comment]
Thanks for the quick confirmation and for sharing the solution, in case someone else runs into a similar issue 🙏 

I'm glad you got it working 🚀 Have an awesome day!

**Comment by cainspencerm** [comment]
@CHC383 Why do you have `thread-stream` included in the external packages? Are you using it explicitly or is this something Pino uses that we need to include? If we need to include it ourselves, does it need to be added to our dependencies? Thanks for the help.

**Comment by CHC383** [comment]
@cainspencerm Please see [Bundling guide in Pino documentation](https://github.com/pinojs/pino/blob/main/docs/bundling.md), specifically it mentions `lib/worker.js from the thread-stream dependency`. It is needed by Pino, and it needs to be in the peerDependencies of your package.json (at least that's my current setup, forgot where I found this solution)

**Comment by cainspencerm** [comment]
@CHC383 Those changes fixed my issue as well. I couldn't find any information on why `thread-stream` should be included outside of that, so your comment has saved me so much time. Thank you!

**Comment by ChrisClaude** [comment]
I spent many hours trying to figure out why I was getting the error below on Vercel 

[@PetrHeinz @CHC383 ](https://github.com/logtail/logtail-js/issues/129#issuecomment-2515296780) is correct. installing logtail fixed it for me

Error: unable to determine transport target for "pino-pretty"
    at fixTarget (/var/task/node_modules/pino/lib/transport.js:160:13)
    at transport (/var/task/node_modules/pino/lib/transport.js:130:22)
    at normalizeArgs (/var/task/node_modules/pino/lib/tools.js:312:16)
    at pino (/var/task/node_modules/pino/pino.js:91:28)
    at createLogger (/var/task/node_modules/@browserbasehq/stagehand/dist/index.js:21646:34)
    at new _StagehandLogger (/var/task/node_modules/@browserbasehq/stagehand/dist/index.js:21658:45)
    at new Stagehand3 (/var/task/node_modules/@browserbasehq/stagehand/dist/index.js:22173:28)
    at Object.handler (/vercel/path0/api/stagehand.ts:62:21)
    at r (/opt/rust/nodejs.js:2:14656)
    at Server.<anonymous> (/opt/rust/nodejs.js:2:11356)

**Comment by dartilesm** [comment]
Did anyone make it work with Turbopack? Any repo sample :( ?
