### ISSUE TITLE
Log message order isn't always accurate

### ISSUE THREAD

**Issue by msafi** [logtail/logtail-js#15]
When messages get batched and dispatched together, they end up with the same timestamp, which causes them to potentially appear in the wrong order on logtail.com.

**Comment by jigglyjams** [comment]
I had this happening to my logs as well! I was using a custom log formatter that removed the milliseconds from the timestamp string. Once I added the milliseconds back in the logs appeared in the proper order!

Hope this helps

**Comment by curusarn** [comment]
Hi @msafi,

I have tried to reproduce this but the logs arrive with the correct timestamps in the correct order:

<img width="599" alt="Screenshot 2023-02-22 at 15 35 04" src="https://user-images.githubusercontent.com/10132717/220654179-0418044b-64c3-44b1-869f-ec9287dcf6c5.png">

I'm closing the issue for now.

Please feel free to reopen and share more information on how to reproduce the issue.
You can always message us at [hello@betterstack.com](mailto:hello@betterstack.com). We're happy to help. 🙏
