### ISSUE TITLE
Please add official support for pino logger

### ISSUE THREAD

**Issue by ItsMrAkhil** [logtail/logtail-js#18]
Next.js, and Winston combination is not working as winston doesn't support async logging. As next.js server inside vercel runs as server less function we need async logging. And pino supports async logging. Please provide an official pino logtail transport plugin. Thanks!

**Comment by kamilcglr** [comment]
Hello, we would also like to use logtail with Pino which is directly integrated in our framework (AdonisJs)

**Comment by smolak** [comment]
I would very much welcome Pino integration as well.

**Comment by flozdra** [comment]
That would be really nice indeed!

**Comment by curusarn** [comment]
Hey everyone, we have just added support for Pino transports [@logtail/pino](https://www.npmjs.com/package/@logtail/pino). 🎉  
You can find quick start guide here: https://betterstack.com/docs/logs/javascript/pino/

The package currently supports [Pino v7+ transports](https://www.nearform.com/blog/pino7-0-0-pino-transport-worker_thread-transport/).
Let me know if you encounter any problems. 🙏   
Fell free to reopen this issue.
