### ISSUE TITLE
Way to disable via environment variable

### ISSUE THREAD

**Issue by KevinBatdorf** [logtail/logtail-js#22]
When developing locally I don't really need to send logging data to Logtail. It would be nice to be able to set the token to `null` and have it just silently continue instead of throwing. `null` being be different from `undefined`, which could have been unintentional.

Is there way convenient way to do this already?

**Comment by curusarn** [comment]
Hi @KevinBatdorf,

Thank you for the suggestion. I will add it to our internal ticketing system.
I will make sure to keep you posted.

**Comment by PetrHeinz** [comment]
Hello @KevinBatdorf,

I'm proposing to add two boolean options (`sendLogsToBetterStack` and `sendLogsToConsoleOutput`) to our logger in https://github.com/logtail/logtail-js/pull/67

When you don't want logs sent to Better Stack you'll be able to initialize with those flags, for example:

```js
const { Logtail } = require("@logtail/node");
const logtail = new Logtail("$SOURCE_TOKEN", {
  sendDataToBetterStack: false,
  sendLogsToConsoleOutput: true,
});

logtail.error("Something bad happend.");
// error will be sent only to console.error()
```

(of course, these flags can be set via ENV variables in the real code)

---

I'll post here the required version when it's merged and released.

**Comment by PetrHeinz** [comment]
Hello @KevinBatdorf,

version `0.4.3` of our JS client [has been released](https://www.npmjs.com/package/@logtail/js/v/0.4.3), which should help you with the configuration you want 🙂

Thanks for bringing it up!
