### ISSUE TITLE
how to contribute

### ISSUE THREAD

**Issue by boly38** [logtail/logtail-js#30]
When I do my first contribution for this repository I regret 2 small things
- have an HowTo contribute to says how to install deps, run jest tests for a given package
- have an automated pipeline to valid my pull request and to play tests.

I thinks github actions must be set in order to do that.

**Comment by adikus** [comment]
@boly38 I've added GitHub action tests as well as a "Contributing" section to the README. Thanks for the feedback!

**Comment by boly38** [comment]
Amazing, good job 👌👏 thanks 🙏
