### ISSUE TITLE
Unable to use logtail with cdn

### ISSUE THREAD

**Issue by markbreuss** [logtail/logtail-js#31]
I simply copied the script tag into the head.

<script src="https://unpkg.com/@logtail/browser@0.31.0/dist/umd/logtail.js"></script>
The window has no attribute Logtail and the console shows the following error:

![image](https://user-images.githubusercontent.com/69714845/210573258-8951076a-56c7-4f80-af7d-d1e155d5963d.png)

Does anyone have experience with using logtail with cdn?

Thanks!

**Comment by adikus** [comment]
Hi @markbreuss! 

Thanks for reaching out. I'm afraid the version in our browser package README is incorrect. Can you try out this instead?
https://unpkg.com/@logtail/browser@0.1.15/dist/umd/logtail.js

In the meantime, I can fix the README.
