### ISSUE TITLE
Extend the Context type in Typescript

### ISSUE THREAD

**Issue by pimmee** [logtail/logtail-js#35]
First of all, I've just started using Logtail and think it's great.

One annoying thing I've found working with the logger from `@logtail/node` is the `Context` type:

```ts
export declare type ContextKey = string | number | boolean | Date | null;
export declare type Context = {
    [key: string]: ContextKey | Context;
};
```

It is too strict to be able to work with conveniently. Some of the issues I've found:

- Context not supporting `undefined` fields
- Context not supporting arrays (e.g. `string[]` or `object[]`)
- Context not supporting `Error`
- Not being able to log error in try/catch (error is typed as `unknown`)

It would be great if Logtail could parse/sanitize these types internally as it would improve the DX a lot. Support for `undefined`, arrays, and try/catch errors (`unknown` type) is highest prio I'd say, as typed errors can be logged as the message argument.

I saw that there was a [PR to sanitize logs](https://github.com/logtail/logtail-js/pull/13), so perhaps some of this is already supported but not reflected in the `ContextKey` type?

Here's a Stackblitz where I demostrate some of the issues: 
https://stackblitz.com/edit/nestjs-typescript-starter-hzo1qb?file=demo.ts

**Comment by adikus** [comment]
Thanks @pimmee for the suggestions. Most of these make sense to me, I'll make a ticket in our internal system so that we can get back to this.

There's couple of things though:
 * I'm not sure if we'd want to support `unknown` types in the library, I would prefer we left that to the user to cast it to `Error` first (but we should defo support `Error`).
 * In your Stackblitz example I noticed that you're doing:
    ```js
    interface Payload2 {
      a: string;
      b?: string;
    }
    const payload2: Payload2 = { a: 'a', b: 'b' };
    logger.info('not working', payload2);
    ```

    One of the following instead should work:
    ```js
    type Payload2 = Record<'a'|'b', string>;
    const payload2: Payload2 = { a: 'a', b: 'b' };
    logger.info('not working', payload2);
    ```

    ```js
    interface Payload2 { [key: string]: string; }
    const payload2: Payload2 = { a: 'a', b: 'b' };
    logger.info('not working', payload2);
    ```

    The problem with the original was that typescript couldn't determine the type of the index, the Context type needs it to be defined as `string`. I realize that these are not the same though and I'm not sure if there's another way to mark the index as string in Typescript while preserving the original interface 😕 .

**Comment by pimmee** [comment]
Thank you for the quick follow up.

- I do think it improves the DX greatly if logtail could handle `unknown` internally, so that we (the users) wouldn't have to do `err as Error` or `if (err instanceof Error)` everywhere where we catch an error and want to log it. 

Also, a lot of projects restricts type assertion with eslint, and we'd have to add disable eslint comments everywhere. This makes it rather cluttered IMO.
```ts
try {
   ...
} catch (err) {
   // eslint-disable-next-line @typescript-eslint/consistent-type-assertions
   logger.error(err as Error);
}
```

In the code within logtail where you sanitize the log data, you could do something like:

```ts
if (value instanceof Error) {
   return value.message; // potentially do something with value.stack to log error stack trace?
}
```

For other `unknown` values that logtail is unable to parse, I'd say they can be ignored as it's unlikely that we'd be able to do anything with it or be interested anyway. 

Maybe even typing Context as `Record<string, unknown>` with logtail parsing/sanitizing everything that it can could work? So basically extending the parsing to handle arrays, etc., so that we can log anything with logtail doing it's best effort to handle it

- I do know that there are other ways of typing objects in Typescript so that they can be logged with logtail. However, a lot of Typescript projects use `undefined` extensively on their interfaces and types. This makes it cumbersome to work with logtail.

Typing an object like the following is a very common way in Typescript for defining optional fields:
```ts
interface Address {
     id: string;
     town: string;
     country: string;
     postal_code: string;
     state?: string;
     floor?: number;
}
```

Not being able to log these objects is a showstopper, so I definitely think it should be supported.

In one project I work on we use the following code snippet, which could perhaps be of inspiration:

```ts
// https://github.com/apollographql/apollo-client/issues/2412#issuecomment-755449680
type RecursivelyReplaceNullWithUndefined<T> = T extends null
  ? undefined
  : {
      [K in keyof T]: T[K] extends (infer U)[]
        ? RecursivelyReplaceNullWithUndefined<U>[]
        : RecursivelyReplaceNullWithUndefined<T[K]>;
    };
/**
 * Recursively removes all null and undefined properties of an object
 * @param input Some object
 * @returns Cleaned object (without null and undefined properties)
 */
export function omitNullishValues<T extends object>(
  input: T
): RecursivelyReplaceNullWithUndefined<T> {
  // See https://stackoverflow.com/questions/37246775/
  const omitByRecursively = (value: object, iteratee: (value: string, key: string) => boolean) => {
    const cb = (v: Record<string, unknown>): unknown => omitByRecursively(v, iteratee);
    return value.constructor.name === 'Object' || value.constructor.name === 'Array'
      ? lodash.isArray(value)
        ? lodash.map(value, cb)
        : lodash(value).omitBy(iteratee).mapValues(cb).value()
      : value;
  };
  // eslint-disable-next-line @typescript-eslint/consistent-type-assertions
  return omitByRecursively(
    input,
    value => value === null || value === undefined
  ) as RecursivelyReplaceNullWithUndefined<T>;
}
```

Let me know if there's anything I can do to help.

**Comment by pimmee** [comment]
Any progress on this @adikus?
