### ISSUE TITLE
Wrong peer dependency in @logtail/node

### ISSUE THREAD

**Issue by andreieuganox** [logtail/logtail-js#37]
As described in PR #36 the used in @logtail/node version restriction for Banyan is absolutely incorrect and points to the Beta version of the package. 
Beta versions are not used by many. 
Moreover, the @logtail/node works absolutely fine with lower versions of Bunyan, and this restriction causes issues with the dependency graph for users using the latest Bunyan (v. 1.8.15).

@trentm can elaborate on this probably more. 

<img width="822" alt="Screenshot 2023-01-23 at 20 05 29" src="https://user-images.githubusercontent.com/29180292/214128687-a9fb0344-43fa-422a-a1dc-a473fe037d46.png">

**Comment by curusarn** [comment]
You are right. There is no need to require the beta version.

Fixed in: https://github.com/logtail/logtail-js/commit/0349d3943d774932b02e7f73aa095b0c9ebc1fed
