### ISSUE TITLE
Extra string added to logs

### ISSUE THREAD

**Issue by jojobean13** [logtail/logtail-js#4]
Every line that's logged has an extra string added to it. Everything starting with the 9 and ending with the 48. How do I get rid of this?
`
2021-11-13 14:34:50.983 [qa] [INFO] 9 ../task/node_modules/@logtail/winston/dist/cjs/winston.js 48 	--> POST /api/stripe

2021-11-13 14:34:51.219 [qa] [INFO] 9 ../task/node_modules/@logtail/winston/dist/cjs/winston.js 48 	Processing Stripe Event: invoice.created.
2021-11-13 14:34:51.268 [qa] [INFO] 9 ../task/node_modules/@logtail/winston/dist/cjs/winston.js 48 	<-- [204] POST /api/stripe 286ms
`

These are the Winston options I have set:
`winston.createLogger({
                level: 'debug', // change to info for prod?
                format: winston.format.combine(
                    winston.format.colorize(),
                    winston.format.align(),
                    winston.format.splat(),
                    winston.format.timestamp({
                        format: customTimeStamp()
                    }),
                    winston.format.printf(customFormat),
                    winston.format.errors({ stack: true }),
                    //winston.format.json() use for non-local?
                )
            })`

Custom format: 
`const customFormat = log => {
    const pattern = /(error|warn|info|http|verbose|debug|silly)/s
    let level = log.level.match(pattern)
    if (level) {
        level = log.level.replace(pattern, level[0].toUpperCase())
    }
    return log.stack ? `${log.timestamp} [${level}]: ${log.message}\n${log.stack}` : `${log.timestamp} [${level}]: ${log.message}`
}`

**Comment by gyfis** [comment]
> Every line that's logged has an extra string added to it. Everything starting with the 9 and ending with the 48. How do I get rid of this? ` 2021-11-13 14:34:50.983 [qa] [INFO] 9 ../task/node_modules/@logtail/winston/dist/cjs/winston.js 48 --> POST /api/stripe
> 
> 2021-11-13 14:34:51.219 [qa] [INFO] 9 ../task/node_modules/@logtail/winston/dist/cjs/winston.js 48 Processing Stripe Event: invoice.created. 2021-11-13 14:34:51.268 [qa] [INFO] 9 ../task/node_modules/@logtail/winston/dist/cjs/winston.js 48 <-- [204] POST /api/stripe 286ms `
> 
> These are the Winston options I have set: `winston.createLogger({ level: 'debug', // change to info for prod? format: winston.format.combine( winston.format.colorize(), winston.format.align(), winston.format.splat(), winston.format.timestamp({ format: customTimeStamp() }), winston.format.printf(customFormat), winston.format.errors({ stack: true }), //winston.format.json() use for non-local? ) })`
> 
> Custom format: `const customFormat = log => { const pattern = /(error|warn|info|http|verbose|debug|silly)/s let level = log.level.match(pattern) if (level) { level = log.level.replace(pattern, level[0].toUpperCase()) } return log.stack ? `${log.timestamp} [${level}]: ${log.message}\n${log.stack}`:`${log.timestamp} [${level}]: ${log.message}` }`

Hi Jo (@jojobean13)! Thanks a lot for your question, and I'm sorry we didn't reply sooner. I believe what you describe here is the Live Tail section of Logtail. You can go to Sources -> advanced settings, and change the fields displayed there by modifying the Live Tail primary fields section of the settings. That should help! 🙌

**Comment by jojobean13** [comment]
That worked, thanks!

*Jo Warren*
Software Engineer at Peachy <http://peachypay.com/> [image: :peach:]
she/her
