### ISSUE TITLE
Updating the context.runtime.file_string context for the Winston logger

### ISSUE THREAD

**Issue by okeeffed** [logtail/logtail-js#5]
Hi! I am playing around with a Next.js app where I am trialling use of Logtail using the [Winston logger](https://www.npmjs.com/package/@logtail/winston) for the backend calls. 

The logs are coming across fine, but the `context.runtime.file_string` is defaulting to the module file i.e. the value resolves to `../../../@logtail/winston/dist/cjs/winston.js` for each call.

I am hoping to update this to the current meta for the file name and line number. Are there any examples for how this works? I have been looking at the [docs](https://docs.logtail.com/integrations/javascript) but am still unable to adjust to context metadata from that example.

Full disclosure: this seems like a misunderstanding of how the configuration works for Winston, given that the [source code](https://github.com/logtail/logtail-js/blob/master/packages/winston/src/winston.ts) looks to simply destructure the `meta` from a Winston `LogEntry` type and I may also be failing to pinpoint the correct overrides needed from Winston itself.

**Comment by gyfis** [comment]
Hi Dennis (@okeeffed), thanks for raising the issue!

I believe we'd need to update the code that locates the correct stack trace - probably by skipping the winston path - to get to the user code space. 

These are the lines that are responsible for locating the correct stack trace today: https://github.com/logtail/logtail-js/blob/master/packages/node/src/context.ts#L34-L41 . Do you feel like submitting a PR for this change?

**Comment by okeeffed** [comment]
Ahhh perfect. Thanks for the speedy reply Tomáš @gyfis ! 

Yep, can definitely submit a PR. It's late here in Australia and I am off tomorrow, but will push up an initial PR this Friday (Australian time).

**Comment by gyfis** [comment]
@okeeffed Sounds great, appreciate it!

**Comment by okeeffed** [comment]
@gyfis are there some docs for contribution or setting up the repo? Forked it to have a look, but unsure on setting up the monorepo. `lerna bootstrap` fails for me on `tsc` and it also looks like this setup isn't supporting Yarn Workspaces, so I am a little confused about whether these are isolated packages or not (both `@logtail/types` and `@logtail/tools` look to be on a different version).

**Comment by okeeffed** [comment]
Just had another look and think I managed my way through - I will push up the PR tonight when I get home.

**Comment by okeeffed** [comment]
@gyfis it turns out that I ran out of time for our spike before I had to move on! Apologies on that. 

The stack trace I was attempting to filter for a PR was too much of a code smell - there was no easy way to confidently find the file that it was invoked from between the Browser and Node version 😞 

My hacky diff (ignoring all the prettier diff) can be seen [here](https://github.com/logtail/logtail-js/compare/master...okeeffed:fix-context-stack-frame-file-name#diff-9c675e355dda1c993b144dc71da187c56ddf8575784478ada5a1d121e3085dbcR39-R66) but you will get what I mean by hacky. 

I was arbitrarily iterating down the stack trace array for the Node version to find what would work but I didn't see any common thread - what I did was fine for the Node tests that I wrote but did not seem very reliable. 

Sorry I wasn't more use! The hacky way was working for my requirements on Node but undoubtably would fail to cover all cases.

**Comment by gyfis** [comment]
> @gyfis it turns out that I ran out of time for our spike before I had to move on! Apologies on that.

That's fine, thanks a lot for your time so far! The team is going to take it over then :) appreciate you letting me know!

**Comment by orbiteleven** [comment]
Any @gyfis update on this? Seeing the same problem. Was the diff/pr that @okeeffed started acceptable? Happy to help iterate on a solution here.

**Comment by adikus** [comment]
@orbiteleven @okeeffed I've released 0.1.12 which should now report the correct line for both the Winston and Bunyan integrations - please give it a go once you are able to!
