### ISSUE TITLE
Question: API query helper

### ISSUE THREAD

**Issue by boly38** [logtail/logtail-js#52]
Hi,
just a question : your documentation talks about ["query" API](https://betterstack.com/docs/logs/query-api/). 

This api is used to get back logs entries from the cloud.

- Does this library (or node one) provides a helper to query logs ? if no do you think it could be a good point ?

It's true that this is very simple to query logs but as we already have a Logtail "source" class, we may have a Logtail "query" class helper too. Or it's just I miss that?

Here is a simple sample of  (1) use the lib to produce log (2) use axios lib to query logs.

If you decide to not introduce helper into this library, you may then maybe add this kind of sample in the documentation?

Best Regards
🤝 to the DEV team + Filip ;) 👍 

````js
// doc : https://docs.logtail.com/integrations/javascript
import { Logtail }  from "@logtail/node";
import axios from "axios";

const action = {
  produceLog: false,
  queryLogs: true
}

function produceLog() {
  const logtailSource = process.env.LOGTAIL_SOURCE;
  // DEBUG // console.log(logtailSource);
  const logtail = new Logtail(logtailSource);
  logtail.info("Logtail installed " + new Date());
}

function queryLogs() {
  const TEAM_TOKEN = process.env.LOGTAIL_TEAM_TOKEN;// pick from logtail team portal : https://logtail.com/team/0/teams/
  const source_ids = process.env.LOGTAIL_SOURCE_IDS || null;// start without then pick source id from result
  const LOGTAIL_BASE_API = 'https://logtail.com/api/v1';
  const Authorization = `Bearer ${TEAM_TOKEN}`;

  const axiosClient = axios.create({
    baseURL: LOGTAIL_BASE_API,
    timeout: 6000,//ms
    headers: { Authorization }
  });

  const params = { source_ids }; // optional

  axiosClient.get("/query", {params}).then(response => {
    var responseText = `/query : status: ${response.status} ${response.statusText}`;
    console.info({res: responseText, data: response.data.data});
  }).catch(err => {
    console.warn("error", err);
  });
}

action.produceLog && produceLog();
action.queryLogs && queryLogs();
````

**Comment by curusarn** [comment]
Hi @boly38,

Thank you for your question and for your example.

I agree that having a helper for querying logs in the library would be convenient.
I have passed the feature request to the team but can't offer any time estimate.
Currently, we think that the HTTP API is easy enough to use.

Let me know if you have more questions. 🙏
Thanks again for reaching out.
