### ISSUE TITLE
LogtailTransport is not assignable to parameter of type 'TransportStream' [winston][typescript]

### ISSUE THREAD

**Issue by Nightbr** [logtail/logtail-js#6]
Hey,

hope you're doing well!

I tried to use the Winston LogtailTransport but I have some Typing issues. 

![image](https://user-images.githubusercontent.com/4228646/154434473-7fe935ce-9ff5-4a97-82a1-c521a3d37db9.png)

```
Argument of type 'LogtailTransport' is not assignable to parameter of type 'TransportStream'.
  Type 'LogtailTransport' is missing the following properties from type 'TransportStream': writable, writableEnded, writableFinished, writableHighWaterMark, and 29 more.
```

Some code ton reproduce this:

```
import * as winston from 'winston';
import * as Transport from 'winston-transport';

// Logtail -> https://logtail.com
import { Logtail } from '@logtail/node';
import { LogtailTransport } from '@logtail/winston';

const logtail = new Logtail('logtail-source-token');

const transports: Transport[] = [];
transports.push(new LogtailTransport(logtail));

const logger = winston.createLogger({
  transports,
  silent: process.env.NODE_ENV === 'test',
});
```

If I change the import of `winston-transport` in winston.ts to `import * as Transport from "winston-transport";`.

Maybe it's a tsconfig with compatibility with old module system but I think there is a lot of project that have this configuration. 

- https://stackoverflow.com/questions/60288465/explaining-semantics-around-module-imports-within-typescript-declaration-files

Thanks for your help, happy to help debug this.

EDIT:

in tsconfig, I added some config to make it works. Maybe worth documenting this :ok_hand: 

```
    "moduleResolution": "node",
    "esModuleInterop": true
```

**Comment by gyfis** [comment]
@Nightbr Thanks for the issue report as well as the steps for resolving it - updated our Winston docs!
