### ISSUE TITLE
Logtail fails gh-action workflows on a javascript boilerplate

### ISSUE THREAD

**Issue by brunolnetto** [logtail/logtail-js#85]
The library `logatail` failts two of my gh-action workflows: 

1. `@logtail/winston`: 
    a. [Build CI](https://github.com/trouchet/sappio/actions/runs/6185715415)
    b. [Coverage CI](https://github.com/trouchet/sappio/actions/runs/6185715416)
2. `@logtail/nide`: 
    a. [Build CI](https://github.com/trouchet/sappio/actions/runs/6185711733)
    b. [Coverage CI](https://github.com/trouchet/sappio/actions/runs/6185711737) 

Image: 
![image](https://github.com/logtail/logtail-js/assets/13961685/eebb824b-0f46-4f19-b67b-23458a327671)

On each of failed workflow runs, the failed step exits likeso:

```
Run actions/setup-node@v3
Attempting to download 19.x...
Not found in manifest. Falling back to download directly from Node
Acquiring 19.9.0 - x64 from https://nodejs.org/dist/v19.9.0/node-v19.9.0-linux-x64.tar.gz
aborted
Waiting 15 seconds before trying again
aborted
Waiting 19 seconds before trying again
Error: aborted
```

**Comment by PetrHeinz** [comment]
Hello @brunolnetto, it seems that your builds fail on setting up Node 19.x, before even installing any of `@logtail` packages.

Some registry might have been down temporarily - I would suggest to rerun the checks...

**Comment by PetrHeinz** [comment]
I can see [the checks failing on `main`](https://github.com/trouchet/sappio/commits/main) as well, the issue doesn't seem to be related to the new release of `@logtail`:

![image](https://github.com/logtail/logtail-js/assets/10008612/75a2b754-d499-4057-8b87-4b682d21690a)

---

I would rerun the checks a few times to make sure failures are consistent. Then, I would rerun the same checks on previously passing commit. If they pass again, you can pinpoint the commit that broke it 🙂

**Comment by brunolnetto** [comment]
It worked like a charm. LoL
