### ISSUE TITLE
Disable @logtail/edge's warning about missing executionCtx when the runtime is not Cloudflare

### ISSUE THREAD

**Issue by MonsterDeveloper** [logtail/logtail-js#88]
Currently, `@logtail/edge` shows a warning if the logger is created without an execution context, and sends a message to Betterstack as well. I couldn't find a way to suppress it.

It'd be nice to have an option to manually suppress this warning. Another approach is determining whether the runtime is Cloudflare Workers ([like here](https://github.com/honojs/hono/blob/3e4f151fa9c91d661fefee808573547d2a2c6862/src/helper/adapter/index.ts#L31)) and showing the warning only if it is.

As a temporary workaround I have to mock an execution context object as follows, so the warning doesn't come up.

```typescript
export const logger = new Logtail("token")
  .withExecutionContext({
    waitUntil() {},
    passThroughOnException() {},
  });
```

**Comment by aroman** [comment]
+1, we need to be able to suppress the warning. actually, _even on cloudflare_ it's often not relevant — for example, using Cloudflare Durable Objects. Even though they use the workers runtime environment, `waitUntil()` is essentially a no-op in a DurableObject, as the DurableObject _does not terminate after the request completes_. Instead, durable objects are terminated after some number of minutes from the last request. So, there's no reason to wrap logging calls in `waitUntil()` in this particular cloudflare environment.

cc: @PetrHeinz sorry I missed this feedback during the PR review stage, I was swamped with other work.

**Comment by PetrHeinz** [comment]
Hi @MonsterDeveloper and @aroman, thanks for feedback on usage outside of my test cases 👍 It would probably be for the best to add an option argument that lets users disable the warning.

By default, I'd still like to have it in. Would you agree with such solution? I'll add the issue to our internal backlog and we should hopefully get to it soon.

Thanks for sharing the workaround as well as extra details on DurableObject 🙌

**Comment by PetrHeinz** [comment]
@MonsterDeveloper I would be definitely nice to detect the runtime first.

Ad Logtail/BetterStack: We'd like to rename the library, but that's quite a lot of effort - it's not just npm packages, but packages for a lot of other languages as well, along with Github repos and the organization. I believe it wouldn't be a priority for some time.

**Comment by PetrHeinz** [comment]
Hi @MonsterDeveloper and @aroman, feel free to update to [`v0.4.14`](https://github.com/logtail/logtail-js/releases/tag/v0.4.14) and use new option `warnAboutMissingExecutionContext: false` to suppress the warning in edge runtime.

See details in #94
