### ISSUE TITLE
Use serialize-error library to seralize errors instead of manually creating an object

### ISSUE THREAD

**Issue by OmG3r** [logtail/logtail-js#90]
Currently error objects are stripped to only `name`, `message` and `stack` properties.

this creates an issue when logging a class that inherits from the `Error` class, all other properties and metadata data added to the custom class are lost.

I would like to propose to use the [serialize-error](https://www.npmjs.com/package/serialize-error) library in order to serialize errors. I am not sure if this is possible since this will add a dependency to the project

**Comment by curusarn** [comment]
Hi @OmG3r,

Thank you for the suggestion!
I've added it to our pipeline. I'll make sure to keep you updated here on GitHub.

Thanks again for reaching out!

**Comment by PetrHeinz** [comment]
Hello @OmG3r and thanks again for the suggestion! 🙌 

I've integrated it in [`v0.4.15`](https://github.com/logtail/logtail-js/releases/tag/v0.4.15), feel free to upgrade!

**Comment by OmG3r** [comment]
Hello @PetrHeinz, Thank you for the addition :pray:, 

is it possible to add this feature to the `node` package too, specifically this line [/logtail/logtail-js/blob/master/packages/node/src/node.ts#L133](https://github.com/logtail/logtail-js/blob/master/packages/node/src/node.ts#L133)

**Comment by PetrHeinz** [comment]
@OmG3r Yeah, that would make sense, thanks for the quick feedback! 👍 I'll reopen the issue and add it there next week.

**Comment by PetrHeinz** [comment]
Hi @OmG3r, for the improved serialization of `Error` objects, update to [`v0.4.16`](https://github.com/logtail/logtail-js/releases/tag/v0.4.16) 🙂
